package com.florintiron.localizegpt

val languageMap = mapOf(
    "af" to "Afrikaans",
    "sq" to "Albanian",
    "am" to "Amharic",
    "ar" to "Arabic",
    "hy-AM" to "Armenian",
    "az-AZ" to "Azerbaijani",
    "bn-BD" to "Bangla",
    "eu-ES" to "Basque",
    "be" to "Belarusian",
    "bg" to "Bulgarian",
    "my-MM" to "Burmese",
    "ca" to "Catalan",
    "zh-HK" to "Chinese (Hong Kong)",
    "zh-CN" to "Chinese (Simplified)",
    "zh-TW" to "Chinese (Traditional)",
    "hr" to "Croatian",
    "cs-CZ" to "Czech",
    "da-DK" to "Danish",
    "nl" to "Dutch",
    "en-IN" to "English",
    "en-SG" to "English",
    "en-ZA" to "English",
    "en-AU" to "English (Australia)",
    "en-CA" to "English (Canada)",
    "en-GB" to "English (United Kingdom)",
    "et" to "Estonian",
    "fil" to "Filipino",
    "fi-FI" to "Finnish",
    "fr-CA" to "French (Canada)",
    "fr-FR" to "French (France)",
    "gl-ES" to "Galician",
    "ka-GE" to "Georgian",
    "de-DE" to "German",
    "el" to "Greek",
    "gu" to "Gujarati",
    "iw-IL" to "Hebrew",
    "hi-IN" to "Hindi",
    "hu-HU" to "Hungarian",
    "is-IS" to "Icelandic",
    "id" to "Indonesian",
    "it-IT" to "Italian",
    "ja-JP" to "Japanese",
    "kn-IN" to "Kannada",
    "kk" to "Kazakh",
    "km-KH" to "Khmer",
    "ko-KR" to "Korean",
    "ky-KG" to "Kyrgyz",
    "lo-LA" to "Lao",
    "lv" to "Latvian",
    "lt" to "Lithuanian",
    "mk-MK" to "Macedonian",
    "ms" to "Malay",
    "ms-MY" to "Malay (Malaysia)",
    "ml-IN" to "Malayalam",
    "mr-IN" to "Marathi",
    "mn-MN" to "Mongolian",
    "ne-NP" to "Nepali",
    "no-NO" to "Norwegian",
    "fa" to "Persian",
    "fa-AE" to "Persian",
    "fa-AF" to "Persian",
    "fa-IR" to "Persian",
    "pl-PL" to "Polish",
    "pt-BR" to "Portuguese (Brazil)",
    "pt-PT" to "Portuguese (Portugal)",
    "pa" to "Punjabi",
    "ro" to "Romanian",
    "rm" to "Romansh",
    "ru" to "Russian",
    "sr" to "Serbian",
    "si-LK" to "Sinhala",
    "sk" to "Slovak",
    "sl" to "Slovenian",
    "es-419" to "Spanish (Latin America)",
    "es-ES" to "Spanish (Spain)",
    "es-US" to "Spanish (United States)",
    "sw" to "Swahili",
    "sv-SE" to "Swedish",
    "ta-IN" to "Tamil",
    "te-IN" to "Telugu",
    "th" to "Thai",
    "tr-TR" to "Turkish",
    "uk" to "Ukrainian",
    "ur" to "Urdu",
    "vi" to "Vietnamese",
    "zu" to "Zulu"
)
