package com.florintiron.localizegpt

val languageMap = mapOf(
    "af" to "Afrikaans",
    "sq" to "Albanian",
    "am" to "Amharic",
    "ar" to "Arabic",
    "hy" to "Armenian",
    "az" to "Azerbaijani",
    "bn" to "Bangla",
    "eu" to "Basque",
    "be" to "Belarusian",
    "bg" to "Bulgarian",
    "my" to "Burmese",
    "ca" to "Catalan",
    "zh" to "Chinese",
    "zh-HK" to "Chinese (Hong Kong)",
    "zh-CN" to "Chinese (Simplified)",
    "zh-TW" to "Chinese (Traditional)",
    "hr" to "Croatian",
    "cs" to "Czech",
    "da" to "Danish",
    "nl" to "Dutch",
    "en" to "English",
    "en-IN" to "English",
    "en-SG" to "English",
    "en-ZA" to "English",
    "en-AU" to "English (Australia)",
    "en-CA" to "English (Canada)",
    "en-GB" to "English (United Kingdom)",
    "et" to "Estonian",
    "fil" to "Filipino",
    "fi" to "Finnish",
    "fr" to "French",
    "fr" to "French",
    "fr-CA" to "French (Canada)",
    "fr-FR" to "French (France)",
    "gl" to "Galician",
    "ka" to "Georgian",
    "de" to "German",
    "el" to "Greek",
    "gu" to "Gujarati",
    "iw" to "Hebrew",
    "hi" to "Hindi",
    "hu" to "Hungarian",
    "is" to "Icelandic",
    "id" to "Indonesian",
    "it" to "Italian",
    "ja" to "Japanese",
    "kn" to "Kannada",
    "kk" to "Kazakh",
    "km" to "Khmer",
    "ko" to "Korean",
    "ky" to "Kyrgyz",
    "lo" to "Lao",
    "lv" to "Latvian",
    "lt" to "Lithuanian",
    "mk" to "Macedonian",
    "ms" to "Malay",
    "ms" to "Malay (Malaysia)",
    "ml" to "Malayalam",
    "mr" to "Marathi",
    "mn" to "Mongolian",
    "ne" to "Nepali",
    "no" to "Norwegian",
    "fa" to "Persian",
    "pl" to "Polish",
    "pt" to "Portuguese",
    "pt-BR" to "Portuguese (Brazil)",
    "pt-PT" to "Portuguese (Portugal)",
    "pa" to "Punjabi",
    "ro" to "Romanian",
    "rm" to "Romansh",
    "ru" to "Russian",
    "sr" to "Serbian",
    "si" to "Sinhala",
    "sk" to "Slovak",
    "sl" to "Slovenian",
    "es" to "Spanish",
    "es-419" to "Spanish (Latin America)",
    "es-ES" to "Spanish (Spain)",
    "es-US" to "Spanish (United States)",
    "sw" to "Swahili",
    "sv" to "Swedish",
    "ta" to "Tamil",
    "te" to "Telugu",
    "th" to "Thai",
    "tr" to "Turkish",
    "uk" to "Ukrainian",
    "ur" to "Urdu",
    "vi" to "Vietnamese",
    "zu" to "Zulu"
)
